version: '3.8'
services:

  nginx:
    build: ./nginx
    ports: 
      - "80:80"
    restart: always
    depends_on:
      - backend
      - frontend
    networks:
      - goals-net
      
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - logs:/app/logs
    networks:
      - goals-net

  frontend:
    build: ./frontend
    depends_on:
      - backend
    networks:
      - goals-net
  
  mongodb:
    image: mongo:7.0
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: tanvir
      MONGO_INITDB_ROOT_PASSWORD: tanvir123
      MONGO_INITDB_DATABASE: GoalsDB
    networks:
      - goals-net

volumes:
  logs:

networks:
  goals-net:
