apiVersion: networking.k8s.io/v1
kind: Ingress
metadata: 
  name: ingress-service 
  namespace: default
spec: 
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: client-clusterip
                port:
                  number: 3000
          - path: /goals
            pathType: Prefix
            backend:
              service:
                name: server-clusterip
                port:
                  number: 5000
