apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec: 
  selector:
    matchLabels:
      app: server
  template: 
    metadata:
      labels:
        app: server
    spec: 
      containers:
      - name: server
        image: tahmed2026/class-backend:0.1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
        volumeMounts:
          - mountPath: /app/logs/
            name: access-log-volume 
        env:
          - name: DATABASE_PASSWORD
            valueFrom: 
              secretKeyRef:
                name: database-secret
                key: password
          - name: DATABASE_USERNAME
            valueFrom:
              secretKeyRef:
                name: database-secret
                key: username
          - name: DATABASE_URL
            valueFrom:
              configMapKeyRef:  
                name: cluster-url 
                key: database
      volumes:
        - name: access-log-volume
          persistentVolumeClaim:
            claimName: backend-log-persistance

---
apiVersion: v1
kind: Service
metadata:
  name: server-clusterip
spec:
  selector:
    app: server
  ports:
  - port: 5000
    targetPort: 5000